# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringpackage',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='home.EventArea'),
            preserve_default=False,
        ),
    ]
