# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170826_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateTimeField(auto_now=True)),
                ('targetdate', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='home.CateringPackages')),
                ('reserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservers', to='home.UserProfileInfo')),
            ],
        ),
    ]
