# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170921_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringpackage',
            name='area',
        ),
    ]
