# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reservation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='foodselections',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
