# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170828_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringpackages',
            name='capacity',
        ),
    ]
