# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_cateringpackages_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='currentdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='targetdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
