# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170828_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='targetdate',
            new_name='eventdate',
        ),
    ]
