# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170828_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.UserProfileInfo'),
        ),
    ]
