# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170912_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cateringpackages',
            old_name='capacity',
            new_name='pax',
        ),
    ]
