# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reservation_eventname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringpackages',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
