# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_cateringpackages_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringpackages',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
