# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170903_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='contact',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
