# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20170912_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='event_time',
            new_name='event_timeend',
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_timestart',
            field=models.TimeField(default='0:00'),
            preserve_default=False,
        ),
    ]
